#!/bin/bash
# Script to finish the rest of FreeSurfer pipeline

usage(){
  echo "  Script to finish the rest of FreeSurfer pipeline."
  echo "    Usage: $(basename $0) <T1 folder path> <Brain masks folder>"
  echo ""
  echo "    <T1 folder path> = Set a folder path which contains all the T1 data to the study."
  echo "    <Manual brain masks folder> = Set a folder path which contains all the manual brain segmentation data to the study."
  echo ""
}

T1_FOLDER=$1
MASK_FOLDER=$2

if [[ $# -lt 2 ]]; then
  usage
  exit
fi

LIST_T1_NAMES=`ls $T1_FOLDER | grep .nii.gz`
if [[ ! -d $T1_FOLDER/FreeSurfer-recon-all ]]; then
  mkdir $T1_FOLDER/FreeSurfer-recon-all
fi
# Run recon-all FreeSurfer
export SUBJECTS_DIR=$T1_FOLDER/FreeSurfer-recon-all
#Freesurfer Analysis
for t1Image in $LIST_T1_NAMES; do
   for maskType in `ls $MASK_FOLDER | grep `echo ${t1Image%.*.*}`_autorecon1_corr`; do
     echo ""
     echo ""
     echo " --> Executing for FreeSurfer brain extraction - mask: $maskType"
     echo ""
     echo ""
     if [[ `echo $maskType | grep _bm_fs` != "" ]]; then
       echo "Entrou no if"
      #  ATLAS=`cat config/config_var.conf | grep ATLAS= | cut -c7-9`
      #  FLOOD=`cat config/config_var.conf | grep FLOOD= | cut -c7-11`
      #  MASK_IMAGE=$MASK_FOLDER/${t1Image%.*.*}_autorecon1_corr_bm_fs_atlas${ATLAS}_h${FLOOD}.nii.gz
      #  #Run the first part of FreeSurfer pipeline - autorecon1 -noskullstrip
      #  recon-all -s ${t1Image%.*.*}_bm_fs_atlas${ATLAS}_h${FLOOD} -i $T1_FOLDER/${t1Image} -autorecon1 -noskullstrip
       #
      #    # Performing the manual skull strip - Using: FreeSurfer brain mask
      #    WHOLE_T1_FOLDER=$T1_FOLDER/FreeSurfer-recon-all/${t1Image%.*.*}_bm_fs_atlas${ATLAS}_h${FLOOD}/mri/
      #    mri_convert -it mgz -ot nii $WHOLE_T1_FOLDER/T1.mgz $WHOLE_T1_FOLDER/T1.nii
      #    gzip -9 $WHOLE_T1_FOLDER/T1.nii
      #    #Effectivelly performing the skull strip on T1 image
      #    fslmaths $WHOLE_T1_FOLDER/T1.nii.gz -mas $MASK_IMAGE $WHOLE_T1_FOLDER/brainmask.auto.nii.gz
      #    # rm $WHOLE_T1_FOLDER/T1.mgz
      #    gzip -d $WHOLE_T1_FOLDER/brainmask.auto.nii.gz
      #    mri_convert -it nii -ot mgz $WHOLE_T1_FOLDER/brainmask.auto.nii $WHOLE_T1_FOLDER/brainmask.auto.mgz
      #    cp $WHOLE_T1_FOLDER/brainmask.auto.mgz $WHOLE_T1_FOLDER/brainmask.mgz
       #
      #    #Running the rest of FreeSurfer pipeline
      #    recon-all -s ${t1Image%.*.*}_bm_fs_atlas${ATLAS}_h${FLOOD} -autorecon2
      #    recon-all -s ${t1Image%.*.*}_bm_fs_atlas${ATLAS}_h${FLOOD} -autorecon3
      #  # fi
     fi


   done
done
