#!/bin/bash
#AFNI brain excration pipeline

#Options variables:


T1_IMAGE=$1
T1_FOLDER=$2
MASK_FOLDER=$3

# Parameters
SHRINK_BOT=`cat config/config_var.conf | grep SHRINK_BOT= | cut -c12-17`
SHRINK_FAC=`cat config/config_var.conf | grep SHRINK_FAC= | cut -c12-17`
PUSH_EDGE=`cat config/config_var.conf | grep PUSH_EDGE= | cut -c11-13`

cd $MASK_FOLDER
#Apply AFNI
if [[ "$PUSH_EDGE" == "Y" ]]; then
  3dSkullStrip -input $T1_FOLDER/${T1_IMAGE}.nii.gz -push_to_edge
else
  if [[ "$SHRINK_FAC" == "" && "$SHRINK_BOT" == "" ]]; then
    3dSkullStrip -input $T1_FOLDER/${T1_IMAGE}.nii.gz
  else
    3dSkullStrip -input $T1_FOLDER/${T1_IMAGE}.nii.gz -shrink_fac_bot_lim $SHRINK_BOT -shrink_fac $SHRINK_FAC
  fi
fi

3dAFNItoNIFTI skull_strip_out+orig.BRIK
# Cleaning trash files
rm *.BRIK *.HEAD

#Transforming the output as binary brain mask
fslmaths skull_strip_out.nii -bin skull_strip_out.nii
#gzip -9 skull_strip_out.nii

#Copying the brain mask to the MASK_FOLDER
#cp $T1_FOLDER/skull_strip_out.nii.gz $MASK_FOLDER/
if [[ "$PUSH_EDGE" == "Y" ]]; then
  mv skull_strip_out.nii.gz ${T1_IMAGE}_bm_afni_pushEdge${PUSH_EDGE}.nii.gz
else
  mv skull_strip_out.nii.gz ${T1_IMAGE}_bm_afni_pushEdge${PUSH_EDGE}_shrFact${SHRINK_FAC}_shrBot${SHRINK_BOT}.nii.gz
fi
rm ./*.nii
cd ~/Documents/brainextraction
