#!/bin/bash
#FreeSurfer brain excration pipeline

#Options variables:
# -atlas use the atlas information to correct the segmentation. When the segmented brain is not correct, this option might help you.
# -T1 specify T1 input volume (T1 grey value = 110)
# -man [int_csf int_trn int_gray] to change the different parameters csf_max, transition_intensity and GM_intensity

T1_IMAGE=$1
T1_FOLDER=$2
MASK_FOLDER=$3

# Parameters
ATLAS=`cat config/config_var.conf | grep ATLAS= | cut -c7-9`
FLOOD=`cat config/config_var.conf | grep FLOOD= | cut -c7-11`

#Apply FreeSurfer
if [[ $ATLAS == "Y"]]; then
  mri_watershed -atlas -h $FLOOD $T1_FOLDER/$T1_IMAGE $T1_FOLDER/${T1_IMAGE}_bm_fs_atlas${ATLAS}_h${FLOOD}.nii.gz
else
  mri_watershed -h $FLOOD $T1_FOLDER/$T1_IMAGE $T1_FOLDER/${T1_IMAGE}_bm_fs_atlas${ATLAS}_h${FLOOD}.nii.gz
fi

#Transforming the output as binary brain mask
fslmaths $T1_FOLDER/${T1_IMAGE}_bm_fs_atlas${ATLAS}_h${FLOOD}.nii.gz -bin $T1_FOLDER/${T1_IMAGE}_bm_fs_atlas${ATLAS}_h${FLOOD}.nii.gz

#Copying the brain mask to the MASK_FOLDER
mv $T1_FOLDER/${T1_IMAGE}_bm_fs_atlas${ATLAS}_h${FLOOD}.nii.gz $MASK_FOLDER/
