#!/bin/bash
#FSL-BET brain excration pipeline

#This method is free of parameters

T1_IMAGE=$1
T1_FOLDER=$2
MASK_FOLDER=$3

#Apply ROBEX
source ROBEX $T1_FOLDER/$T1_IMAGE $T1_FOLDER/${T1_IMAGE}_bm_robex.nii.gz

#Transforming the output as binary brain mask
fslmaths $T1_FOLDER/${T1_IMAGE}_bm_robex.nii.gz -bin $T1_FOLDER/${T1_IMAGE}_bm_robex.nii.gz

#Moving the brain mask to the MASK_FOLDER
mv $T1_FOLDER/${T1_IMAGE}_bm_robex.nii.gz $MASK_FOLDER/
